"""
Self-Hint Manager for MobileForge Rollout

This module manages the retrieval and formatting of hints for the self-hint 
feature in rollout mode. Hints are generated by the evaluator when an attempt 
fails and are passed to subsequent attempts of the same task.

Hints are stored as eval_hint.json files in each attempt directory.
Hints only flow within a single task - they are not shared between different tasks.
"""

import os
import json
from typing import List, Dict, Optional
import logging


class HintManager:
    """Manages hints for self-hint functionality in rollout mode."""

    def __init__(self, output_dir: str, task_identifier: str, agent_name: str):
        """
        Initialize HintManager for a specific task.

        Args:
            output_dir: Base output directory for the session
            task_identifier: Unique identifier for the task
            agent_name: Name of the agent being used
        """
        self.output_dir = output_dir
        self.task_identifier = task_identifier
        self.agent_name = agent_name
        self.task_dir = os.path.join(output_dir, task_identifier, agent_name)

    def get_hints_for_attempt(self, current_attempt: int) -> List[Dict]:
        """
        Get all hints from previous attempts to use for the current attempt.
        Reads eval_hint.json files from previous attempt directories.

        Args:
            current_attempt: The current attempt number

        Returns:
            List of hint dictionaries from attempts < current_attempt
        """
        previous_hints = []

        for attempt_num in range(1, current_attempt):
            attempt_dir = os.path.join(self.task_dir, f"attempt_{attempt_num}")
            hint_file = os.path.join(attempt_dir, "eval_hint.json")

            if os.path.exists(hint_file):
                try:
                    with open(hint_file, "r", encoding="utf-8") as f:
                        hint_data = json.load(f)
                        hint_data["attempt"] = attempt_num
                        previous_hints.append(hint_data)
                except (json.JSONDecodeError, IOError) as e:
                    logging.warning(
                        f"[HintManager] Failed to load hint from {hint_file}: {e}"
                    )

        return previous_hints

    def format_hints_for_prompt(self, current_attempt: int) -> str:
        """
        Format hints from previous attempts into a string suitable for agent prompts.
        Uses the structured hint format generated by LLM.

        Args:
            current_attempt: The current attempt number

        Returns:
            Formatted string containing all previous hints
        """
        previous_hints = self.get_hints_for_attempt(current_attempt)

        if not previous_hints:
            return ""

        # Format hints for prompt with structured information
        formatted_lines = [
            "\n" + "=" * 80,
            "EVALUATION HINTS FROM PREVIOUS ATTEMPTS",
            "=" * 80,
            "The following insights come from analysis of previous failed attempts.",
            "Please review these carefully to avoid repeating the same mistakes:\n",
        ]

        for hint_entry in previous_hints:
            attempt_num = hint_entry.get("attempt", "?")
            formatted_lines.append(f"--- Hint from Attempt #{attempt_num} ---\n")

            # Add hint summary (most important)
            hint_summary = hint_entry.get("hint_summary", "")
            if hint_summary:
                formatted_lines.append(f"Summary: {hint_summary}\n")

            # Add key mistake
            key_mistake = hint_entry.get("key_mistake", "")
            if key_mistake:
                formatted_lines.append(f"Key Mistake: {key_mistake}\n")

            # Add what to avoid
            what_to_avoid = hint_entry.get("what_to_avoid", [])
            if what_to_avoid:
                formatted_lines.append("What to Avoid:")
                for item in what_to_avoid:
                    formatted_lines.append(f"  - {item}")
                formatted_lines.append("")

            # Add suggested approach
            suggested_approach = hint_entry.get("suggested_approach", [])
            if suggested_approach:
                formatted_lines.append("Suggested Approach:")
                for item in suggested_approach:
                    formatted_lines.append(f"  - {item}")
                formatted_lines.append("")

            # Add important insights
            important_insights = hint_entry.get("important_insights", [])
            if important_insights:
                formatted_lines.append("Important Insights:")
                for item in important_insights:
                    formatted_lines.append(f"  - {item}")
                formatted_lines.append("")

        formatted_lines.append("=" * 80)
        formatted_lines.append("END OF EVALUATION HINTS")
        formatted_lines.append("=" * 80 + "\n")

        return "\n".join(formatted_lines)

    def clear_hints(self):
        """Clear all hints for this task (useful when overwriting results)."""
        # Since hints are now stored in eval_hint.json files in each attempt directory,
        # clearing hints means removing these files from all attempt directories
        if not os.path.exists(self.task_dir):
            return

        for item in os.listdir(self.task_dir):
            attempt_dir = os.path.join(self.task_dir, item)
            if os.path.isdir(attempt_dir) and item.startswith("attempt_"):
                hint_file = os.path.join(attempt_dir, "eval_hint.json")
                if os.path.exists(hint_file):
                    os.remove(hint_file)
                    logging.info(f"[HintManager] Cleared hint: {hint_file}")


def get_hints_for_agent(
    output_dir: str, task_identifier: str, agent_name: str, current_attempt: int
) -> str:
    """
    Convenience function to get formatted hints for an agent.

    Args:
        output_dir: Base output directory for the session
        task_identifier: Unique identifier for the task
        agent_name: Name of the agent
        current_attempt: The current attempt number

    Returns:
        Formatted hints string for including in agent prompts
    """
    hint_manager = HintManager(output_dir, task_identifier, agent_name)
    hints = hint_manager.format_hints_for_prompt(current_attempt)
    
    if hints:
        hint_count = len(hint_manager.get_hints_for_attempt(current_attempt))
        logging.info(
            f"[HintManager] Loaded {hint_count} hint(s) for task {task_identifier}, attempt {current_attempt}"
        )
    
    return hints


def load_hint_from_attempt(
    output_dir: str, task_identifier: str, agent_name: str, attempt_num: int
) -> Optional[Dict]:
    """
    Load a specific hint from an attempt directory.

    Args:
        output_dir: Base output directory for the session
        task_identifier: Unique identifier for the task
        agent_name: Name of the agent
        attempt_num: The attempt number to load hint from

    Returns:
        Hint dictionary if found, None otherwise
    """
    attempt_dir = os.path.join(
        output_dir, task_identifier, agent_name, f"attempt_{attempt_num}"
    )
    hint_file = os.path.join(attempt_dir, "eval_hint.json")

    if not os.path.exists(hint_file):
        return None

    try:
        with open(hint_file, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError) as e:
        logging.warning(f"[HintManager] Failed to load hint from {hint_file}: {e}")
        return None
